# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test-gh-pages',
                'doc_host': 'https://seeM.github.io',
                'git_url': 'https://github.com/seeM/test-gh-pages',
                'lib_path': 'test_gh_pages'},
  'syms': {'test_gh_pages.core': {'test_gh_pages.core.foo': ('core.html#foo', 'test_gh_pages/core.py')}}}